# Generated by Django 5.1.4 on 2024-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catagory",
            new_name="Category",
        ),
    ]
