# Generated by Django 5.1.4 on 2024-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_price_product_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
